<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/images/favicon.ico" type="content/x-icon">
    <title>Choir Manager</title>
</head>
<style>
    div{
        height: 35%;
        width: 100%;
        background: #f2f2f2;
    }
    body {
        background-color: #bbbfd6 ;
    }
</style>
<body>
<br><br>
<div>
    <br>
    <br>
    <h1 align="center"><font size="5" face="Microsoft YaHei">${message}</font></h1>
</div>
</body>
</html>