<html lang="ru">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="/images/favicon.ico" type="content/x-icon">
    <title>Choir Manager</title>
</head>
<body>
<h1>Добро пожаловать в Chorus Manager</h1>
<p>Это веб-приложение поможет вам в управлении вашим хором</p>

<form method="get" action="/auth/login">
    <button type="submit">Войти</button>
</form>

<form method="get" action="/registration">
    <button type="submit">Регистрация</button>
</form>

</body>
</html>
