<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="/images/favicon.ico" type="content/x-icon">
    <title>Choir Manager</title>
</head>
<body>
<h1>Welcome to the Chorus Manager</h1>
<p>This web-application help you to manage your choir</p>

<form method="get" action="/auth/login">
    <button type="submit">Login</button>
</form>

<form method="get" action="/registration">
    <button type="submit">Registration</button>
</form>

</body>
</html>
